config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users

  resources :emails, only: [:index, :show, :destroy] do
    post :batch, on: :collection
  end
  
  resources :metadata_mappings

  resources :filters do
    patch :enable, on: :member
    patch :disable, on: :member
    resources :conditions do
      patch :enable, on: :member
      patch :disable, on: :member
    end
    resources :operations do
      patch :enable, on: :member
      patch :disable, on: :member
    end
  end

  root to: "emails#index"

  mount Sidekiq::Web => '/sidekiq'
end

app/models/condition.rb
# frozen_string_literal: true

class Condition < ApplicationRecord
  belongs_to :filter

  scope :enabled, -> { where(enabled: true) }

  validates :property_type, presence: true
end

app/controllers/conditions_controller.rb
class ConditionsController < ApplicationController
  before_action :set_filter
  before_action :set_condition, only: [:show, :edit, :update, :destroy, :enable, :disable]

  # GET /conditions
  def index
    @conditions = @filter.conditions.all
  end

  # GET /conditions/1
  def show
  end

  # GET /conditions/new
  def new
    @condition = @filter.conditions.new
  end

  # GET /conditions/1/edit
  def edit
  end

  # POST /conditions
  def create
    @condition = @filter.conditions.new(condition_params)

    if @condition.save
      redirect_to @filter, notice: 'Filter was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /conditions/1
  def update
    if @condition.update(condition_params)
      redirect_to @filter, notice: 'Filter was successfully updated.'
    else
      render :edit
    end
  end

  def enable
    if @condition.update(enabled: true)
      redirect_to @filter, notice: 'Condition was successfully enabled.'
    else
      render :edit
    end
  end

  def disable
    if @condition.update(enabled: false)
      redirect_to @filter, notice: 'Condition was successfully disabled.'
    else
      render :edit
    end
  end

  # DELETE /conditions/1
  def destroy
    @condition.destroy
    redirect_to @filter, notice: 'Filter was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between conditions.
    def set_filter
      @filter = Filter.find(params[:filter_id])
    end
    def set_condition
      @condition = @filter.conditions.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def condition_params
      params.require(:condition).permit(:enabled, :property_type, :property_value, :test_method, :test_value, :inverted)
    end
end

app/helpers/conditions_helper.rb
module ConditionsHelper
end

app/views/conditions/_condition.html.erb
<div id="<%= dom_id condition %>" class="flex flex-cols">

  <div class="flex-auto text-left">
    <% if condition.enabled? %>
      <!-- Enabled: "bg-indigo-600", Not Enabled: "bg-gray-200" -->
      <%= link_to disable_filter_condition_path(condition.filter, condition), data: { method: :patch, confirm: 'Are you sure you want to disable this condition?' }, class: "bg-green-400 relative inline-flex flex-shrink-0 h-6 w-11 border-2 border-transparent rounded-full cursor-pointer transition-colors ease-in-out duration-200 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-green-500", "aria-pressed":"false" do %>
        <span class="sr-only">Disable</span>
        <!-- Enabled: "translate-x-5", Not Enabled: "translate-x-0" -->
        <span aria-hidden="true" class="translate-x-5 pointer-events-none inline-block h-5 w-5 rounded-full bg-white shadow transform ring-0 transition ease-in-out duration-200"></span>
      <% end %>
    <% else %>
      <%= link_to enable_filter_condition_path(condition.filter, condition), data: { method: :patch, confirm: 'Are you sure you want to disable this condition?' }, class: "bg-gray-200 relative inline-flex flex-shrink-0 h-6 w-11 border-2 border-transparent rounded-full cursor-pointer transition-colors ease-in-out duration-200 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-green-500", "aria-pressed":"false" do %>
        <span class="sr-only">Enable</span>
        <!-- Enabled: "translate-x-5", Not Enabled: "translate-x-0" -->
        <span aria-hidden="true" class="translate-x-0 pointer-events-none inline-block h-5 w-5 rounded-full bg-white shadow transform ring-0 transition ease-in-out duration-200"></span>
      <% end %>
    <% end %>
  </div>

  <div class="flex-auto text-left">
    <strong>Property type:</strong>
    <%= condition.property_type %>
  </div>

  <div class="flex-auto text-left">
    <strong>Property value:</strong>
    <%= condition.property_value %>
  </div>

  <div class="flex-auto text-left">
    <strong>Test method:</strong>
    <%= condition.test_method %>
  </div>

  <div class="flex-auto text-left">
    <strong>Test value:</strong>
    <%= condition.test_value %>
  </div>

  <div class="flex-auto text-left">
    <strong>Inverted:</strong>
    <%= condition.inverted %>
  </div>
</div>

app/views/conditions/_form.html.erb
<%= form_with(model: [ condition.filter, condition ],
      data: { controller: "reset_form", action: "turbo:submit-end->reset_form#reset" }) do |form| %>
  <%= render(FormErrorsComponent.new(errors: condition.errors)) do %>
    <%= pluralize(condition.errors.count, "error") %> prohibited this condition from being saved:
  <% end if condition.errors.any? %>

  <div class="field flex items-center">
    <fieldset>
      <legend class="block text-sm font-medium text-gray-700">Enabled?</legend>
      <div class="mt-4 space-y-4">
        <div class="flex items-start">
          <div class="flex items-center h-5">
            <%= form.radio_button :enabled, true, class: "focus:ring-indigo-500 h-4 w-4 text-indigo-600 border-gray-300" %>
          </div>
          <div class="ml-3 text-sm">
            <%= form.label :enabled_true, "Yes", class: "font-medium text-gray-700" %>
          </div>
        </div>
        <div class="flex items-start">
          <div class="flex items-center h-5">
            <%= form.radio_button :enabled, false, class: "focus:ring-indigo-500 h-4 w-4 text-indigo-600 border-gray-300" %>
          </div>
          <div class="ml-3 text-sm">
            <%= form.label :enabled_false, "No", class: "font-medium text-gray-700" %>
          </div>
        </div>
      </div>
    </fieldset>
  </div>

  <div class="field flex items-center">
    <fieldset>
      <legend class="block text-sm font-medium text-gray-700">Property type</legend>
      <div class="mt-4 space-y-4">
        <div class="flex items-start">
          <div class="flex items-center h-5">
            <%= form.radio_button :property_type, "header", class: "focus:ring-indigo-500 h-4 w-4 text-indigo-600 border-gray-300" %>
          </div>
          <div class="ml-3 text-sm">
            <%= form.label :property_type_header, "Header", class: "font-medium text-gray-700" %>
          </div>
        </div>
        <div class="flex items-start">
          <div class="flex items-center h-5">
            <%= form.radio_button :property_type, "body", class: "focus:ring-indigo-500 h-4 w-4 text-indigo-600 border-gray-300" %>
          </div>
          <div class="ml-3 text-sm">
            <%= form.label :property_type_body, "Body", class: "font-medium text-gray-700" %>
          </div>
        </div>
      </div>
    </fieldset>
  </div>

  <div class="field">
    <%= form.label :property_value, class: "block text-sm font-medium text-gray-700" %>
    <%= form.text_field :property_value, class: "mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md" %>
  </div>

  <div class="field">
    <%= form.label :test_method, class: "block text-sm font-medium text-gray-700" %>
    <%= form.select :test_method, I18n.t("condition.test_methods").map { |key, value| [value, key] }, {}, class: "mt-1 block w-full py-2 px-3 border border-gray-300 bg-white rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm" %>
  </div>

  <div class="field">
    <%= form.label :test_value, class: "block text-sm font-medium text-gray-700" %>
    <%= form.text_field :test_value, class: "mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md" %>
  </div>

  <div class="field flex items-center">
    <fieldset>
      <legend class="block text-sm font-medium text-gray-700">Inverted?</legend>
      <div class="mt-4 space-y-4">
        <div class="flex items-start">
          <div class="flex items-center h-5">
            <%= form.radio_button :inverted, true, class: "focus:ring-indigo-500 h-4 w-4 text-indigo-600 border-gray-300" %>
          </div>
          <div class="ml-3 text-sm">
            <%= form.label :inverted_true, "Yes", class: "font-medium text-gray-700" %>
          </div>
        </div>
        <div class="flex items-start">
          <div class="flex items-center h-5">
            <%= form.radio_button :inverted, false, class: "focus:ring-indigo-500 h-4 w-4 text-indigo-600 border-gray-300" %>
          </div>
          <div class="ml-3 text-sm">
            <%= form.label :inverted_false, "No", class: "font-medium text-gray-700" %>
          </div>
        </div>
      </div>
    </fieldset>
  </div>

  <div class="actions">
    <%= form.submit class: "inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" %>
  </div>
<% end %>

app/views/conditions/edit.html.erb
<h1>Editing Condition</h1>

<%= render 'form', condition: @condition %>

<%= link_to 'Show', @condition %> |
<%= link_to 'Back', @condition.filter %>

app/views/conditions/index.html.erb
<%= render(FlashNoticeComponent.new) { notice } if notice.present? %>

<h1>Conditions</h1>

<table>
  <thead>
    <tr>
      <th>Enabled</th>
      <th>Property type</th>
      <th>Property value</th>
      <th>Test method</th>
      <th>Test value</th>
      <th>Inverted</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @conditions.each do |condition| %>
      <tr>
        <td><%= condition.enabled %></td>
        <td><%= condition.property_type %></td>
        <td><%= condition.property_value %></td>
        <td><%= condition.test_method %></td>
        <td><%= condition.test_value %></td>
        <td><%= condition.inverted %></td>
        <td><%= link_to 'Show', condition %></td>
        <td><%= link_to 'Edit', edit_condition_path(condition) %></td>
        <td><%= link_to 'Destroy', condition, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Condition', new_condition_path %>

app/views/conditions/new.html.erb
<h1>New Condition</h1>

<%= turbo_frame_tag "new_condition", target: "_top" do %>
  <%= render 'form', condition: @condition %>
<% end %>

<%= link_to 'Back', @condition.filter %>

app/views/conditions/show.html.erb
<%= render(FlashNoticeComponent.new) { notice } if notice.present? %>

<%= render @condition %>

<%= link_to 'Edit', edit_condition_path(@condition) %> |
<%= link_to 'Back', @condition.filter %>