config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users

  resources :emails, only: [:index, :show, :destroy] do
    post :batch, on: :collection
  end
  
  resources :metadata_mappings

  resources :filters do
    patch :enable, on: :member
    patch :disable, on: :member
    resources :conditions do
      patch :enable, on: :member
      patch :disable, on: :member
    end
    resources :operations do
      patch :enable, on: :member
      patch :disable, on: :member
    end
  end

  root to: "emails#index"

  mount Sidekiq::Web => '/sidekiq'
end

app/models/metadata_mapping.rb
# frozen_string_literal: true

class MetadataMapping < ApplicationRecord
end

app/controllers/metadata_mappings_controller.rb
class MetadataMappingsController < ApplicationController
  before_action :set_metadata_mapping, only: [:show, :edit, :update, :destroy]

  # GET /metadata_mappings
  def index
    @metadata_mappings = MetadataMapping.all.order(organisation: :asc, server: :asc, input: :asc)
  end

  # GET /metadata_mappings/1
  def show
  end

  # GET /metadata_mappings/new
  def new
    @metadata_mapping = MetadataMapping.new
  end

  # GET /metadata_mappings/1/edit
  def edit
  end

  # POST /metadata_mappings
  def create
    @metadata_mapping = MetadataMapping.new(metadata_mapping_params)

    if @metadata_mapping.save
      redirect_to @metadata_mapping, notice: 'Metadata mapping was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /metadata_mappings/1
  def update
    if @metadata_mapping.update(metadata_mapping_params)
      redirect_to @metadata_mapping, notice: 'Metadata mapping was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /metadata_mappings/1
  # DELETE /metadata_mappings/1.json
  def destroy
    @metadata_mapping.destroy
    redirect_to metadata_mappings_url, notice: 'Metadata mapping was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_metadata_mapping
      @metadata_mapping = MetadataMapping.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def metadata_mapping_params
      params.require(:metadata_mapping).permit(:input, :server, :organisation)
    end
end

app/helpers/metadata_mappings_helper.rb
module MetadataMappingsHelper
end

app/views/metadata_mappings/_form.html.erb
<%= form_with(model: metadata_mapping) do |form| %>
  <% if metadata_mapping.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(metadata_mapping.errors.count, "error") %> prohibited this metadata_mapping from being saved:</h2>

      <ul>
        <% metadata_mapping.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :input %>
    <%= form.text_field :input %>
  </div>

  <div class="field">
    <%= form.label :server %>
    <%= form.text_field :server %>
  </div>

  <div class="field">
    <%= form.label :organisation %>
    <%= form.text_field :organisation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/metadata_mappings/edit.html.erb
<h1>Editing Metadata Mapping</h1>

<%= render 'form', metadata_mapping: @metadata_mapping %>

<%= link_to 'Show', @metadata_mapping %> |
<%= link_to 'Back', metadata_mappings_path %>

app/views/metadata_mappings/index.html.erb
<%= render(FlashNoticeComponent.new) { notice } if notice.present? %>

<h1>Metadata Mappings</h1>

<table>
  <thead>
    <tr>
      <th>Input</th>
      <th>Server</th>
      <th>Organisation</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @metadata_mappings.each do |metadata_mapping| %>
      <tr>
        <td><%= metadata_mapping.input %></td>
        <td><%= metadata_mapping.server %></td>
        <td><%= metadata_mapping.organisation %></td>
        <td><%= link_to 'Show', metadata_mapping %></td>
        <td><%= link_to 'Edit', edit_metadata_mapping_path(metadata_mapping) %></td>
        <td><%= link_to 'Destroy', metadata_mapping, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Metadata Mapping', new_metadata_mapping_path %>

app/views/metadata_mappings/new.html.erb
<h1>New Metadata Mapping</h1>

<%= render 'form', metadata_mapping: @metadata_mapping %>

<%= link_to 'Back', metadata_mappings_path %>

app/views/metadata_mappings/show.html.erb
<%= render(FlashNoticeComponent.new) { notice } if notice.present? %>

<p>
  <strong>Input:</strong>
  <%= @metadata_mapping.input %>
</p>

<p>
  <strong>Server:</strong>
  <%= @metadata_mapping.server %>
</p>

<p>
  <strong>Organisation:</strong>
  <%= @metadata_mapping.organisation %>
</p>

<%= link_to 'Edit', edit_metadata_mapping_path(@metadata_mapping) %> |
<%= link_to 'Back', metadata_mappings_path %>