config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users

  resources :emails, only: [:index, :show, :destroy] do
    post :batch, on: :collection
  end
  
  resources :metadata_mappings

  resources :filters do
    patch :enable, on: :member
    patch :disable, on: :member
    resources :conditions do
      patch :enable, on: :member
      patch :disable, on: :member
    end
    resources :operations do
      patch :enable, on: :member
      patch :disable, on: :member
    end
  end

  root to: "emails#index"

  mount Sidekiq::Web => '/sidekiq'
end

app/models/filter.rb
# frozen_string_literal: true

class Filter < ApplicationRecord
  has_many :conditions, dependent: :destroy
  has_many :operations, dependent: :destroy
  
  validates :description, presence: true

  scope :enabled, -> { where(enabled: true) }
end

app/controllers/filters_controller.rb
class FiltersController < ApplicationController
  before_action :set_filter, only: [:show, :edit, :update, :destroy, :enable, :disable]

  # GET /filters
  def index
    @filters = Filter.all
  end

  # GET /filters/1
  def show
  end

  # GET /filters/new
  def new
    @filter = Filter.new
  end

  # GET /filters/1/edit
  def edit
  end

  # POST /filters
  def create
    @filter = Filter.new(filter_params)

    if @filter.save
      redirect_to @filter, notice: 'Filter was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /filters/1
  def update
    if @filter.update(filter_params)
      redirect_to @filter, notice: 'Filter was successfully updated.'
    else
      render :edit
    end
  end

  def enable
    if @filter.update(enabled: true)
      redirect_to @filter, notice: 'Filter was successfully enabled.'
    else
      render :edit
    end
  end

  def disable
    if @filter.update(enabled: false)
      redirect_to @filter, notice: 'Filter was successfully disabled.'
    else
      render :edit
    end
  end

  # DELETE /filters/1
  def destroy
    @filter.destroy
    redirect_to filters_url, notice: 'Filter was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_filter
      @filter = Filter.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def filter_params
      params.require(:filter).permit(:description, :enabled, :operator, :inverted)
    end
end

app/helpers/filters_helper.rb
module FiltersHelper
end

app/views/filters/_filter.html.erb
<div id="<%= dom_id filter %>" class="<%= filter.enabled? ? 'filter--enabled' : 'filter--disabled' %> flex space-x-2">

  <div class="flex-auto">
    <strong class="pr-1">Description:</strong>
    <%= filter.description || "<i>No description</i>".html_safe %>
  </div>

  <div class="flex-auto">
    <strong class="pr-1">Operator:</strong>
    <%= filter.operator %>
  </div>

  <div class="flex-auto">
    <strong class="pr-1">Inverted:</strong>
    <%= filter.inverted? ? 'Yes' : 'No' %>
  </div>
</div>

app/views/filters/_form.html.erb
<%= turbo_frame_tag "filter" do %>
  <%= form_with(model: filter) do |form| %>
    <%= render(FormErrorsComponent.new(errors: filter.errors)) do %>
      <%= pluralize(filter.errors.count, "error") %> prohibited this filter from being saved:
    <% end if filter.errors.any? %>

    <div class="field">
      <%= form.label :description, class: "block text-sm font-medium text-gray-700" %>
      <%= form.text_field :description, class: "mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md" %>
    </div>

    <div class="field flex items-center">
      <fieldset>
        <legend class="block text-sm font-medium text-gray-700">Enabled?</legend>
        <div class="mt-4 space-y-4">
          <div class="flex items-start">
            <div class="flex items-center h-5">
              <%= form.radio_button :enabled, true, class: "focus:ring-indigo-500 h-4 w-4 text-indigo-600 border-gray-300" %>
            </div>
            <div class="ml-3 text-sm">
              <%= form.label :enabled_true, "Yes", class: "font-medium text-gray-700" %>
            </div>
          </div>
          <div class="flex items-start">
            <div class="flex items-center h-5">
              <%= form.radio_button :enabled, false, class: "focus:ring-indigo-500 h-4 w-4 text-indigo-600 border-gray-300" %>
            </div>
            <div class="ml-3 text-sm">
              <%= form.label :enabled_false, "No", class: "font-medium text-gray-700" %>
            </div>
          </div>
        </div>
      </fieldset>
    </div>

    <div class="field flex items-center">
      <fieldset>
        <legend class="block text-sm font-medium text-gray-700">Operator</legend>
        <div class="mt-4 space-y-4">
          <div class="flex items-start">
            <div class="flex items-center h-5">
              <%= form.radio_button :operator, "AND", class: "focus:ring-indigo-500 h-4 w-4 text-indigo-600 border-gray-300" %>
            </div>
            <div class="ml-3 text-sm">
              <%= form.label :operator_and, "AND", class: "font-medium text-gray-700" %>
            </div>
          </div>
          <div class="flex items-start">
            <div class="flex items-center h-5">
              <%= form.radio_button :operator, "OR", class: "focus:ring-indigo-500 h-4 w-4 text-indigo-600 border-gray-300" %>
            </div>
            <div class="ml-3 text-sm">
              <%= form.label :operator_or, "OR", class: "font-medium text-gray-700" %>
            </div>
          </div>
        </div>
      </fieldset>
    </div>

    <div class="field flex items-center">
      <fieldset>
        <legend class="block text-sm font-medium text-gray-700">Inverted?</legend>
        <div class="mt-4 space-y-4">
          <div class="flex items-start">
            <div class="flex items-center h-5">
              <%= form.radio_button :inverted, true, class: "focus:ring-indigo-500 h-4 w-4 text-indigo-600 border-gray-300" %>
            </div>
            <div class="ml-3 text-sm">
              <%= form.label :inverted_true, "Yes", class: "font-medium text-gray-700" %>
            </div>
          </div>
          <div class="flex items-start">
            <div class="flex items-center h-5">
              <%= form.radio_button :inverted, false, class: "focus:ring-indigo-500 h-4 w-4 text-indigo-600 border-gray-300" %>
            </div>
            <div class="ml-3 text-sm">
              <%= form.label :inverted_false, "No", class: "font-medium text-gray-700" %>
            </div>
          </div>
        </div>
      </fieldset>
    </div>

    <div class="actions">
      <%= form.submit class: "inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" %>
    </div>
  <% end %>
<% end %>

app/views/filters/edit.html.erb
<h1>Editing Filter</h1>

<%= render 'form', filter: @filter %>

<%= link_to 'Show', @filter %> |
<%= link_to 'Back', filters_path %>

app/views/filters/index.html.erb
<% content_for :main_header do %>
  <h1>Filters</h1>
<% end %>

<%= render(FlashNoticeComponent.new) { notice } if notice.present? %>

<div class="shadow overflow-hidden border-b border-gray-200 rounded-lg">
  <table class="min-w-full divide-y divide-gray-200">
    <thead class="bg-gray-50">
      <tr>
        <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Description</th>
        <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Enabled</th>
        <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Operator</th>
        <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Inverted</th>
        <th scope="col" class="relative px-6 py-3"><span class="sr-only">Show, Edit, Destroy</span></th>
      </tr>
    </thead>

    <tbody class="bg-white divide-y divide-gray-200">
      <% @filters.each do |filter| %>
        <tr class="<%= cycle('bg-white', 'bg-gray-50', :name => 'zebra') %>">
          <td class="px-6 py-4 whitespace-nowrap">
            <%= filter.description %>
          </td>
          <td class="px-6 py-4 whitespace-nowrap">
            <% if filter.enabled? %>
              <!-- Enabled: "bg-indigo-600", Not Enabled: "bg-gray-200" -->
              <%= link_to disable_filter_path(filter), data: { method: :patch, confirm: 'Are you sure you want to disable this filter?' }, class: "bg-green-400 relative inline-flex flex-shrink-0 h-6 w-11 border-2 border-transparent rounded-full cursor-pointer transition-colors ease-in-out duration-200 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500", "aria-pressed":"false" do %>
                <span class="sr-only">Disable</span>
                <!-- Enabled: "translate-x-5", Not Enabled: "translate-x-0" -->
                <span aria-hidden="true" class="translate-x-5 pointer-events-none inline-block h-5 w-5 rounded-full bg-white shadow transform ring-0 transition ease-in-out duration-200"></span>
              <% end %>
            <% else %>
              <%= link_to enable_filter_path(filter), data: { method: :patch, confirm: 'Are you sure you want to disable this filter?' }, class: "bg-gray-200 relative inline-flex flex-shrink-0 h-6 w-11 border-2 border-transparent rounded-full cursor-pointer transition-colors ease-in-out duration-200 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500", "aria-pressed":"false" do %>
                <span class="sr-only">Enable</span>
                <!-- Enabled: "translate-x-5", Not Enabled: "translate-x-0" -->
                <span aria-hidden="true" class="translate-x-0 pointer-events-none inline-block h-5 w-5 rounded-full bg-white shadow transform ring-0 transition ease-in-out duration-200"></span>
              <% end %>
            <% end %>
          </td>
          <td class="px-6 py-4 whitespace-nowrap">
            <%= filter.operator %>
          </td>
          <td class="px-6 py-4 whitespace-nowrap">
            <%= filter.inverted %>
          </td>
          <td>
            <%= link_to 'Show', filter %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<br>

<%= link_to 'New Filter', new_filter_path %>

app/views/filters/new.html.erb
<h1>New Filter</h1>

<%= render 'form', filter: @filter %>

<%= link_to 'Back', filters_path %>

app/views/filters/show.html.erb
<% content_for :main_header do %>
  <h1 class="truncate">Filter #<%= @filter.id %>: <%= @filter.description %></h1>
<% end %>

<div class="grid grid-cols-3 gap-6">

<div class="shadow rounded-lg bg-white">
  <h2 class="text-xl py-2 font-medium text-center bg-gray-50 border-b border-gray-300 rounded-t-lg">Filter</h2>
  <div class="px-4 py-3">
    <%= render(FlashNoticeComponent.new) { notice } if notice.present? %>

    <%= turbo_frame_tag "filter" do %>
      <%= render @filter %>
    <% end %>

    <div class="my-4 flex items-center">
      <div class="flex-1 flex justify-end space-x-4">
        <%= link_to 'Edit', edit_filter_path(@filter), class: "rounded-md relative inline-flex items-center px-4 py-2 border border-gray-100 bg-white text-sm font-medium text-gray-700 hover:bg-gray-200 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-gray-500" %>

        <% if @filter.enabled? %>
          <%= link_to "Disable", disable_filter_path(@filter), data: { method: :patch, confirm: 'Are you sure you want to disable this filter?' }, class: "rounded-md relative inline-flex items-center px-4 py-2 border border-transparent bg-yellow-200 text-sm font-medium text-yellow-700 hover:bg-yellow-300 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-yellow-500" %>
        <% else %>
          <%= link_to "Enable", enable_filter_path(@filter), data: { method: :patch, confirm: 'Are you sure you want to disable this filter?' }, class: "rounded-md relative inline-flex items-center px-4 py-2 border border-transparent bg-green-50 text-sm font-medium text-green-700 hover:bg-green-200 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-green-500" %>
        <% end %>

        <%= link_to 'Delete', @filter, method: :delete, data: { confirm: 'Are you sure you want to delete this filter? There is no undo!' }, class: "rounded-md relative inline-flex items-center px-4 py-2 border border-transparent bg-white text-sm font-medium text-red-700 bg-red-100 hover:bg-red-200 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-red-500" %>
      </div>
    </div>
  </div>

</div>


<div class="shadow rounded-lg bg-white">
  <h2 class="text-xl py-2 font-medium text-center bg-gray-50 border-b border-gray-300 rounded-t-lg">Conditions</h2>
  <div class="px-4 py-3">
    <%= render(@filter.conditions) || "<i class='italic'>No conditions yet</i>".html_safe %>

    <%= turbo_frame_tag "new_condition" do %>
      <div>
        <%= link_to "Add a new condition", new_filter_condition_path(@filter) %>
      </div>
    <% end %>
  </div>
</div>

<div class="shadow rounded-lg bg-white">
  <h2 class="text-xl py-2 font-medium text-center bg-gray-50 border-b border-gray-300 rounded-t-lg">Operations</h2>
  <div class="px-4 py-3 bg-white">
    <%= render(@filter.operations) || "<i class='italic'>No operations yet</i>".html_safe %>
    <%= turbo_frame_tag "new_operation" do %>
      <div>
        <%= link_to "Add a new operation", new_filter_operation_path(@filter) %>
      </div>
    <% end %>
  </div>
</div>



</div>