config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users

  resources :emails, only: [:index, :show, :destroy] do
    post :batch, on: :collection
  end
  
  resources :metadata_mappings

  resources :filters do
    patch :enable, on: :member
    patch :disable, on: :member
    resources :conditions do
      patch :enable, on: :member
      patch :disable, on: :member
    end
    resources :operations do
      patch :enable, on: :member
      patch :disable, on: :member
    end
  end

  root to: "emails#index"

  mount Sidekiq::Web => '/sidekiq'
end

app/models/operation.rb
# frozen_string_literal: true

class Operation < ApplicationRecord
  belongs_to :filter

  scope :enabled, -> { where(enabled: true) }
end

app/controllers/operations_controller.rb
class OperationsController < ApplicationController
  before_action :set_filter
  before_action :set_operation, only: [:show, :edit, :update, :destroy, :enable, :disable]

  # GET /operations
  def index
    @operations = @filter.operations.all
  end

  # GET /operations/1
  def show
  end

  # GET /operations/new
  def new
    @operation = @filter.operations.new
  end

  # GET /operations/1/edit
  def edit
  end

  # POST /operations
  def create
    @operation = @filter.operations.new(operation_params)

    if @operation.save
      redirect_to @filter, notice: 'Operation was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /operations/1
  def update
    if @operation.update(operation_params)
      redirect_to @filter, notice: 'Operation was successfully updated.'
    else
      render :edit
    end
  end

  def enable
    if @operation.update(enabled: true)
      redirect_to @filter, notice: 'Operation was successfully enabled.'
    else
      render :edit
    end
  end

  def disable
    if @operation.update(enabled: false)
      redirect_to @filter, notice: 'Operation was successfully disabled.'
    else
      render :edit
    end
  end

  # DELETE /operations/1
  def destroy
    @operation.destroy
    redirect_to @filter, notice: 'Operation was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between operations.
    def set_filter
      @filter = Filter.find(params[:filter_id])
    end
    def set_operation
      @operation = @filter.operations.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def operation_params
      params.require(:operation).permit(:enabled, :class_name, :argument)
    end
end

app/helpers/operations_helper.rb
module OperationsHelper
end

app/views/operations/_form.html.erb
<%= form_with(model: [ operation.filter, operation ],
      data: { controller: "reset_form", operation: "turbo:submit-end->reset_form#reset" }) do |form| %>
  <%= render(FormErrorsComponent.new(errors: operation.errors)) do %>
    <%= pluralize(operation.errors.count, "error") %> prohibited this operation from being saved:
  <% end if operation.errors.any? %>

  <div class="field flex items-center">
    <fieldset>
      <legend class="block text-sm font-medium text-gray-700">Enabled?</legend>
      <div class="mt-4 space-y-4">
        <div class="flex items-start">
          <div class="flex items-center h-5">
            <%= form.radio_button :enabled, true, class: "focus:ring-indigo-500 h-4 w-4 text-indigo-600 border-gray-300" %>
          </div>
          <div class="ml-3 text-sm">
            <%= form.label :enabled_true, "Yes", class: "font-medium text-gray-700" %>
          </div>
        </div>
        <div class="flex items-start">
          <div class="flex items-center h-5">
            <%= form.radio_button :enabled, false, class: "focus:ring-indigo-500 h-4 w-4 text-indigo-600 border-gray-300" %>
          </div>
          <div class="ml-3 text-sm">
            <%= form.label :enabled_false, "No", class: "font-medium text-gray-700" %>
          </div>
        </div>
      </div>
    </fieldset>
  </div>

  <div class="field">
    <%= form.label :class_name, class: "block text-sm font-medium text-gray-700" %>
    <%= form.text_field :class_name, class: "mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md" %>
  </div>

  <div class="field">
    <%= form.label :argument, class: "block text-sm font-medium text-gray-700" %>
    <%= form.text_field :argument, class: "mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md" %>
  </div>

  <div class="operations">
    <%= form.submit class: "inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" %>
  </div>
<% end %>

app/views/operations/_operation.html.erb
<div id="<%= dom_id operation %>" class="flex flex-cols">

  <div class="flex-auto text-left">
    <% if operation.enabled? %>
      <!-- Enabled: "bg-indigo-600", Not Enabled: "bg-gray-200" -->
      <%= link_to disable_filter_operation_path(operation.filter, operation), data: { method: :patch, confirm: 'Are you sure you want to disable this operation?' }, class: "bg-green-400 relative inline-flex flex-shrink-0 h-6 w-11 border-2 border-transparent rounded-full cursor-pointer transition-colors ease-in-out duration-200 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-green-500", "aria-pressed":"false" do %>
        <span class="sr-only">Disable</span>
        <!-- Enabled: "translate-x-5", Not Enabled: "translate-x-0" -->
        <span aria-hidden="true" class="translate-x-5 pointer-events-none inline-block h-5 w-5 rounded-full bg-white shadow transform ring-0 transition ease-in-out duration-200"></span>
      <% end %>
    <% else %>
      <%= link_to enable_filter_operation_path(operation.filter, operation), data: { method: :patch, confirm: 'Are you sure you want to disable this operation?' }, class: "bg-gray-200 relative inline-flex flex-shrink-0 h-6 w-11 border-2 border-transparent rounded-full cursor-pointer transition-colors ease-in-out duration-200 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-green-500", "aria-pressed":"false" do %>
        <span class="sr-only">Enable</span>
        <!-- Enabled: "translate-x-5", Not Enabled: "translate-x-0" -->
        <span aria-hidden="true" class="translate-x-0 pointer-events-none inline-block h-5 w-5 rounded-full bg-white shadow transform ring-0 transition ease-in-out duration-200"></span>
      <% end %>
    <% end %>
  </div>

  <div class="flex-auto text-left">
    <strong class="pr-1">Class name:</strong>
    <%= operation.class_name %>
  </div>

  <div class="flex-auto text-left">
    <strong class="pr-1">Argument:</strong>
    <%= operation.argument %>
  </div>
</div>

app/views/operations/edit.html.erb
<h1>Editing Operation</h1>

<%= render 'form', operation: @operation %>

<%= link_to 'Show', @operation %> |
<%= link_to 'Back', @operation.filter %>

app/views/operations/index.html.erb
<%= render(FlashNoticeComponent.new) { notice } if notice.present? %>

<h1>Operations</h1>

<table>
  <thead>
    <tr>
      <th>Enabled</th>
      <th>Class name</th>
      <th>Argument</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @operations.each do |operation| %>
      <tr>
        <td><%= operation.enabled %></td>
        <td><%= operation.class_name %></td>
        <td><%= operation.argument %></td>
        <td><%= link_to 'Show', operation %></td>
        <td><%= link_to 'Edit', edit_operation_path(operation) %></td>
        <td><%= link_to 'Destroy', operation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Operation', new_operation_path %>

app/views/operations/new.html.erb
<h1>New Operation</h1>

<%= turbo_frame_tag "new_operation", target: "_top" do %>
  <%= render 'form', operation: @operation %>
<% end %>

<%= link_to 'Back', @operation.filter %>

app/views/operations/show.html.erb
<%= render(FlashNoticeComponent.new) { notice } if notice.present? %>

<%= render @operation %>

<%= link_to 'Edit', edit_operation_path(@operation) %> |
<%= link_to 'Back', @operation.filter %>